syntax = "proto3";

message MqMessage {
  int32 version = 1;
  string message_id = 2;
  string message_type = 3;
  bytes message = 4;
  bytes signature = 5;
  string receiver_node_id = 6;
  string sender_node_id = 7;
  string message_compression_algorithm = 8;
}

message ConsentRequestMqMessage {
  string request_json = 1;
  string request_message_data_url_prefix = 2;
  bytes request_message_bytes = 3;
}

message AsDataResponseMqMessage {
  string request_json = 1;
  string packed_data_metadata = 2;
  bytes packed_data_bytes = 3;
}