FROM node:24-alpine3.23 AS builder

# Fix issue with dependency installation sometimes silently failing due to Node.js Happy Eyeballs issue. 
# Node.js's fetch fails with "AggregateError [ETIMEDOUT]" when running "node-gyp rebuild" while downloading node headers from https://unofficial-builds.nodejs.org 
# causing dependency install to not work properly.
# More info: https://r1ch.net/blog/node-v20-aggregateeerror-etimedout-happy-eyeballs
ENV NODE_OPTIONS="--no-network-family-autoselection"

WORKDIR /api

# RUN sed -i -e 's/http:/https:/' /etc/apk/repositories

RUN apk update && apk add --no-cache --virtual .build-deps \
  python3 \
  g++ \
  make \
  git \
  file

COPY ./ndid-logger/package*.json /api/ndid-logger/
COPY ./telemetry/package*.json /api/telemetry/

WORKDIR /api/ndid-logger
RUN npm ci
RUN npm prune --production

WORKDIR /api/telemetry
RUN npm ci

COPY ./ndid-error /api/ndid-error
COPY ./ndid-logger /api/ndid-logger
COPY ./telemetry /api/telemetry

RUN npm run build

RUN npm prune --production

RUN apk del .build-deps


FROM node:24-alpine3.23
LABEL maintainer="NDID IT Team <it@ndid.co.th>"

# Set umask to 027
RUN umask 027 && echo "umask 0027" >> /etc/profile

# RUN sed -i -e 's/http:/https:/' /etc/apk/repositories
COPY --from=builder /var/cache/apk /var/cache/apk
RUN apk add --no-cache bash openssl && rm -rf /var/cache/apk

COPY --from=builder /api/ndid-error /api/ndid-error
COPY --from=builder /api/ndid-logger /api/ndid-logger
COPY --from=builder /api/telemetry /api/telemetry

COPY ./protos /api/protos
COPY COPYING /api/
COPY VERSION /api/

WORKDIR /api/telemetry

ENTRYPOINT [ "node", "/api/telemetry/build/index.js" ]
