FROM node:24-alpine3.24 AS builder

# Fix issue with dependency installation sometimes silently failing due to Node.js Happy Eyeballs issue. 
# Node.js's fetch fails with "AggregateError [ETIMEDOUT]" when running "node-gyp rebuild" while downloading node headers from https://unofficial-builds.nodejs.org 
# causing dependency install to not work properly.
# More info: https://r1ch.net/blog/node-v20-aggregateeerror-etimedout-happy-eyeballs
ENV NODE_OPTIONS="--no-network-family-autoselection"

WORKDIR /api

# RUN sed -i -e 's/http:/https:/' /etc/apk/repositories

RUN apk update && apk add --no-cache \
  python3 \
  g++ \
  make \
  git

COPY ./ndid-error/package*.json /api/ndid-error/  
COPY ./ndid-logger/package*.json /api/ndid-logger/
COPY ./mq-server/package*.json /api/mq-server/

WORKDIR /api/ndid-error
RUN npm ci --omit=dev

WORKDIR /api/ndid-logger
RUN npm ci --omit=dev

WORKDIR /api/mq-server
RUN npm ci

COPY ./ndid-error /api/ndid-error
COPY ./ndid-logger /api/ndid-logger
COPY ./mq-server /api/mq-server

RUN npm run build

RUN npm prune --production


FROM node:24-alpine3.24
LABEL maintainer="NDID IT Team <it@ndid.co.th>"

# Set umask to 027
RUN umask 027 && echo "umask 0027" >> /etc/profile

# RUN sed -i -e 's/http:/https:/' /etc/apk/repositories
RUN apk add --no-cache bash

# Remove non-essential package management binaries
RUN rm -rf /usr/local/bin/npm \
           /usr/local/bin/npx \
           /usr/local/bin/yarn \
           /usr/local/bin/yarnpkg \
           /usr/local/bin/corepack \
           /usr/local/lib/node_modules/npm \
           /usr/local/lib/node_modules/corepack \
           /root/.npm \
           /root/.yarn

COPY --from=builder /api/ndid-error /api/ndid-error
COPY --from=builder /api/ndid-logger /api/ndid-logger
COPY --from=builder /api/mq-server /api/mq-server

COPY ./protos /api/protos
COPY COPYING /api/
COPY VERSION /api/

WORKDIR /api/mq-server

ENTRYPOINT [ "node", "/api/mq-server/build/server.js" ]
