version: '3'
services:
  telemetry-client-proxy-1:
    image: ndidplatform/telemetry-client:${DOCKER_TAG:-latest}
    environment:
      - NODE_ID=proxy1_rp4,proxy1_idp4,proxy1_as4
      - TELEMETRY_DB_HOST=api-redis-proxy-1
      - TELEMETRY_DB_PORT=6379
      - TELEMETRY_NODE_GRPC_HOST=${TELEMETRY_NODE_GRPC_HOST:-ndid-telemetry-server}
      - TELEMETRY_NODE_GRPC_PORT=${TELEMETRY_NODE_GRPC_PORT-8880}
      - FLUSH_INTERVAL_SEC=20
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform

  telemetry-client-proxy-2:
    image: ndidplatform/telemetry-client:${DOCKER_TAG:-latest}
    environment:
      - NODE_ID=proxy2_rp5
      - TELEMETRY_DB_HOST=api-redis-proxy-2
      - TELEMETRY_DB_PORT=6379
      - TELEMETRY_NODE_GRPC_HOST=${TELEMETRY_NODE_GRPC_HOST:-ndid-telemetry-server}
      - TELEMETRY_NODE_GRPC_PORT=${TELEMETRY_NODE_GRPC_PORT-8880}
      - FLUSH_INTERVAL_SEC=20
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform

networks:
  ndidplatform:
