version: '3'
services:
  api-ndid:
    image: ndidplatform/api:${DOCKER_TAG:-latest}
    environment:
      - ROLE=ndid
      - NODE_ID=ndid1
      - NDID_IP=api-ndid
      - TENDERMINT_IP=tm-1
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
      - DB_IP=api-redis
      - SERVER_PORT=${API_PORT:-8080}
      - NDID_NODE=true
      - ENABLE_TELEMETRY_LOGGING=false
      - ENABLE_CONFIG_HTTP_ROUTE_PATH=true
    volumes:
      - ./start-api-test.sh:/api/start-api-test.sh
    entrypoint: /api/start-api-test.sh
    security_opt:
      - no-new-privileges
    user: root
    ports:
      - "8080:${API_PORT:-8080}"
    networks:
      - ndidplatform
  api-idp-1:
    image: ndidplatform/api:${DOCKER_TAG:-latest}
    environment:
      - ROLE=idp
      - NODE_ID=idp1
      - NDID_IP=api-ndid
      - TENDERMINT_IP=tm-1
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
      - MQ_CONTACT_IP=mq-idp-1
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - MQ_SERVICE_SERVER_IP=mq-idp-1
      - DB_IP=api-redis
      - SERVER_PORT=${API_PORT:-8080}
      - ENABLE_TELEMETRY_LOGGING=true
      - ENABLE_CONFIG_HTTP_ROUTE_PATH=true
    volumes:
      - ./start-api-test.sh:/api/start-api-test.sh
    entrypoint: /api/start-api-test.sh
    security_opt:
      - no-new-privileges
    user: root
    ports:
      - "8100:${API_PORT:-8080}"
    networks:
      - ndidplatform
  api-idp-2:
    image: ndidplatform/api:${DOCKER_TAG:-latest}
    environment:
      - ROLE=idp
      - NODE_ID=idp2
      - NDID_IP=api-ndid
      - TENDERMINT_IP=tm-1
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
      - MQ_CONTACT_IP=mq-idp-2
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - MQ_SERVICE_SERVER_IP=mq-idp-2
      - DB_IP=api-redis
      - SERVER_PORT=${API_PORT:-8080}
      - ENABLE_TELEMETRY_LOGGING=true
      - ENABLE_CONFIG_HTTP_ROUTE_PATH=true
    volumes:
      - ./start-api-test.sh:/api/start-api-test.sh
    entrypoint: /api/start-api-test.sh
    security_opt:
      - no-new-privileges
    user: root
    ports:
      - "8101:${API_PORT:-8080}"
    networks:
      - ndidplatform
  api-idp-3:
    image: ndidplatform/api:${DOCKER_TAG:-latest}
    environment:
      - ROLE=idp
      - NODE_ID=idp3
      - NDID_IP=api-ndid
      - TENDERMINT_IP=tm-1
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
      - MQ_CONTACT_IP=mq-idp-3
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - MQ_SERVICE_SERVER_IP=mq-idp-3
      - DB_IP=api-redis
      - SERVER_PORT=${API_PORT:-8080}
      - ENABLE_TELEMETRY_LOGGING=true
      - ENABLE_CONFIG_HTTP_ROUTE_PATH=true
    volumes:
      - ./start-api-test.sh:/api/start-api-test.sh
    entrypoint: /api/start-api-test.sh
    security_opt:
      - no-new-privileges
    user: root
    ports:
      - "8102:${API_PORT:-8080}"
    networks:
      - ndidplatform
  api-rp-1:
    image: ndidplatform/api:${DOCKER_TAG:-latest}
    environment:
      - ROLE=rp
      - NODE_ID=rp1
      - NDID_IP=api-ndid
      - TENDERMINT_IP=tm-2
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
      - MQ_CONTACT_IP=mq-rp-1
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - MQ_SERVICE_SERVER_IP=mq-rp-1
      - DB_IP=api-redis
      - SERVER_PORT=${API_PORT:-8080}
      - ENABLE_TELEMETRY_LOGGING=true
      - ENABLE_CONFIG_HTTP_ROUTE_PATH=true
    volumes:
      - ./start-api-test.sh:/api/start-api-test.sh
    entrypoint: /api/start-api-test.sh
    security_opt:
      - no-new-privileges
    user: root
    ports:
      - "8200:${API_PORT:-8080}"
    networks:
      - ndidplatform
  api-rp-2:
    image: ndidplatform/api:${DOCKER_TAG:-latest}
    environment:
      - ROLE=rp
      - NODE_ID=rp2
      - NDID_IP=api-ndid
      - TENDERMINT_IP=tm-2
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
      - MQ_CONTACT_IP=mq-rp-2
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - MQ_SERVICE_SERVER_IP=mq-rp-2
      - DB_IP=api-redis
      - SERVER_PORT=${API_PORT:-8080}
      - ENABLE_TELEMETRY_LOGGING=true
      - ENABLE_CONFIG_HTTP_ROUTE_PATH=true
    volumes:
      - ./start-api-test.sh:/api/start-api-test.sh
    entrypoint: /api/start-api-test.sh
    security_opt:
      - no-new-privileges
    user: root
    ports:
      - "8201:${API_PORT:-8080}"
    networks:
      - ndidplatform
  api-as-1:
    image: ndidplatform/api:${DOCKER_TAG:-latest}
    environment:
      - ROLE=as
      - NODE_ID=as1
      - NDID_IP=api-ndid
      - TENDERMINT_IP=tm-3
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
      - MQ_CONTACT_IP=mq-as-1
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - MQ_SERVICE_SERVER_IP=mq-as-1
      - DB_IP=api-redis
      - SERVER_PORT=${API_PORT:-8080}
      - ENABLE_TELEMETRY_LOGGING=true
      - ENABLE_CONFIG_HTTP_ROUTE_PATH=true
    volumes:
      - ./start-api-test.sh:/api/start-api-test.sh
    entrypoint: /api/start-api-test.sh
    security_opt:
      - no-new-privileges
    user: root
    ports:
      - "8300:${API_PORT:-8080}"
    networks:
      - ndidplatform
  api-as-2:
    image: ndidplatform/api:${DOCKER_TAG:-latest}
    environment:
      - ROLE=as
      - NODE_ID=as2
      - NDID_IP=api-ndid
      - TENDERMINT_IP=tm-3
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
      - MQ_CONTACT_IP=mq-as-2
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - MQ_SERVICE_SERVER_IP=mq-as-2
      - DB_IP=api-redis
      - SERVER_PORT=${API_PORT:-8080}
      - ENABLE_TELEMETRY_LOGGING=true
      - ENABLE_CONFIG_HTTP_ROUTE_PATH=true
    volumes:
      - ./start-api-test.sh:/api/start-api-test.sh
    entrypoint: /api/start-api-test.sh
    security_opt:
      - no-new-privileges
    user: root
    ports:
      - "8301:${API_PORT:-8080}"
    networks:
      - ndidplatform
  api-proxy-1:
    image: ndidplatform/api:${DOCKER_TAG:-latest}
    environment:
      - ROLE=proxy
      - NODE_ID=proxy1
      - NDID_IP=api-ndid
      - TENDERMINT_IP=tm-4
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
      - MQ_CONTACT_IP=mq-proxy-1
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - MQ_SERVICE_SERVER_IP=mq-proxy-1
      - DB_IP=api-redis-proxy-1
      - SERVER_PORT=${API_PORT:-8080}
      - ENABLE_TELEMETRY_LOGGING=true
      - ENABLE_CONFIG_HTTP_ROUTE_PATH=true
    volumes:
      - ./start-api-test.sh:/api/start-api-test.sh
    entrypoint: /api/start-api-test.sh
    security_opt:
      - no-new-privileges
    user: root
    ports:
      - "8400:${API_PORT:-8080}"
    networks:
      - ndidplatform
  api-proxy-2:
    image: ndidplatform/api:${DOCKER_TAG:-latest}
    environment:
      - ROLE=proxy
      - NODE_ID=proxy2
      - NDID_IP=api-ndid
      - TENDERMINT_IP=tm-4
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
      - MQ_CONTACT_IP=mq-proxy-2
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - MQ_SERVICE_SERVER_IP=mq-proxy-2
      - DB_IP=api-redis-proxy-2
      - SERVER_PORT=${API_PORT:-8080}
      - ENABLE_TELEMETRY_LOGGING=true
      - ENABLE_CONFIG_HTTP_ROUTE_PATH=true
    volumes:
      - ./start-api-test.sh:/api/start-api-test.sh
    entrypoint: /api/start-api-test.sh
    security_opt:
      - no-new-privileges
    user: root
    ports:
      - "8401:${API_PORT:-8080}"
    networks:
      - ndidplatform

  # redis
  api-redis:
    image: redis:5-alpine
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
  api-redis-proxy-1:
    image: redis:5-alpine
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
  api-redis-proxy-2:
    image: redis:5-alpine
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform

  # MQ service server containers
  mq-idp-1:
    image: ndidplatform/mq:${DOCKER_TAG:-latest}
    environment:
      - NODE_ID=idp1
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - SERVER_PORT=${MQ_SERVER_PORT:-50051}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    ulimits:
      nofile: 
        soft: 30000
        hard: 30000
  mq-idp-2:
    image: ndidplatform/mq:${DOCKER_TAG:-latest}
    environment:
      - NODE_ID=idp2
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - SERVER_PORT=${MQ_SERVER_PORT:-50051}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    ulimits:
      nofile: 
        soft: 30000
        hard: 30000
  mq-idp-3:
    image: ndidplatform/mq:${DOCKER_TAG:-latest}
    environment:
      - NODE_ID=idp3
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - SERVER_PORT=${MQ_SERVER_PORT:-50051}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    ulimits:
      nofile: 
        soft: 30000
        hard: 30000
  mq-rp-1:
    image: ndidplatform/mq:${DOCKER_TAG:-latest}
    environment:
      - NODE_ID=rp1
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - SERVER_PORT=${MQ_SERVER_PORT:-50051}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    ulimits:
      nofile: 
        soft: 30000
        hard: 30000
  mq-rp-2:
    image: ndidplatform/mq:${DOCKER_TAG:-latest}
    environment:
      - NODE_ID=rp2
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - SERVER_PORT=${MQ_SERVER_PORT:-50051}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    ulimits:
      nofile: 
        soft: 30000
        hard: 30000
  mq-as-1:
    image: ndidplatform/mq:${DOCKER_TAG:-latest}
    environment:
      - NODE_ID=as1
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - SERVER_PORT=${MQ_SERVER_PORT:-50051}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    ulimits:
      nofile: 
        soft: 30000
        hard: 30000
  mq-as-2:
    image: ndidplatform/mq:${DOCKER_TAG:-latest}
    environment:
      - NODE_ID=as2
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - SERVER_PORT=${MQ_SERVER_PORT:-50051}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    ulimits:
      nofile: 
        soft: 30000
        hard: 30000
  mq-proxy-1:
    image: ndidplatform/mq:${DOCKER_TAG:-latest}
    environment:
      - NODE_ID=proxy1
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - SERVER_PORT=${MQ_SERVER_PORT:-50051}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    ulimits:
      nofile: 
        soft: 30000
        hard: 30000
  mq-proxy-2:
    image: ndidplatform/mq:${DOCKER_TAG:-latest}
    environment:
      - NODE_ID=proxy2
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - SERVER_PORT=${MQ_SERVER_PORT:-50051}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    ulimits:
      nofile: 
        soft: 30000
        hard: 30000

networks:
  ndidplatform:
